# Generated by Django 4.1.3 on 2023-02-26 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='作者')),
                ('age', models.IntegerField(verbose_name='享年')),
                ('fly_level', models.IntegerField(blank=True, verbose_name='ヤバイ度')),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='国名')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Sects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='派')),
            ],
            options={
                'db_table': 'sects',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='作品名')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authors')),
                ('sect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.sects')),
            ],
            options={
                'db_table': 'works',
            },
        ),
        migrations.AddField(
            model_name='authors',
            name='countries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.countries'),
        ),
        migrations.AddField(
            model_name='authors',
            name='sects',
            field=models.ManyToManyField(to='authors.sects'),
        ),
    ]
