# Generated by Django 4.1.3 on 2023-02-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_authors_countries_alter_works_sect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='countries',
            field=models.CharField(max_length=20, verbose_name='国名'),
        ),
    ]
