# Generated by Django 4.1.3 on 2023-03-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='works',
            new_name='work',
        ),
    ]
